- src/main/java/org/passay/AbstractDictionaryRule.java
- src/main/java/org/passay/dictionary/Dictionary.java
- src/main/java/org/passay/dictionary/TernaryTreeDictionary.java
- src/main/java/org/passay/dictionary/WordListDictionary.java
- src/main/java/org/passay/entropy/ShannonEntropyFactory.java
- src/test/java/org/passay/PasswordValidatorTest.java
I've added a couple minor changes:
- Dictionary should not be instantiated with a null.
- Dictionary interface should return its size.
Reason for those changes was to ensure that we don't flag a Shannon entropy estimate with a supplied empty dictionary.
PS: I love a resolution where there are more deletions than additions :+1:
> ISSUE-37 improve precision of ShannonEntropyFactory

- .gitattributes
- src/main/checkstyle/checks.xml
- src/main/java/org/passay/dictionary/AbstractFileWordList.java
- src/main/java/org/passay/dictionary/FileWordList.java
- src/main/java/org/passay/dictionary/MemoryMappedFileWordList.java
- src/test/java/org/passay/dictionary/AbstractWordListTest.java
- src/test/java/org/passay/dictionary/ArrayWordListDictionaryPerfTest.java
- src/test/java/org/passay/dictionary/ArrayWordListTest.java
- src/test/java/org/passay/dictionary/FileWordListTest.java
- src/test/java/org/passay/dictionary/MemoryMappedFileWordListDictionaryPerfTest.java
- src/test/java/org/passay/dictionary/MemoryMappedFileWordListTest.java
- src/test/resources/newlines.dos
- src/test/resources/newlines.mac
- src/test/resources/newlines.unix
- src/test/testng/testng.xml
Improve FileWordList by using BufferReader in #readFile.
Change the meaning of cachePercent to apply to file size rather than number of lines.
(It's meaning was never well defined.)
This allows the cache to be built inline while reading the file, removing the need to read the file twice.
This will generally result in larger caches, but users can tune the cache size down if that is an issue.
> Add MemmoryMappedFileWordList.

- src/main/java/org/passay/AllowedCharacterRule.java
- src/main/java/org/passay/IllegalCharacterRule.java
- src/main/java/org/passay/IllegalRegexRule.java
- src/main/java/org/passay/IllegalSequenceRule.java
- src/main/java/org/passay/RepeatCharacterRegexRule.java
- src/test/java/org/passay/AllowedCharacterRuleTest.java
- src/test/java/org/passay/IllegalCharacterRuleTest.java
- src/test/java/org/passay/IllegalRegexRuleTest.java
- src/test/java/org/passay/RepeatCharacterRegexRuleTest.java
These rules only reported the first failure, provided a switch to control the behavior.
Also implemented a check so duplicate failures are not reported.
Note that this changes the default behavior for these rules.
Also conformed the implementations of AllowedCharacterRule and IllegalCharacterRule, both use a binary search now.
> Allow reporting of all failures for these rules.

- pom.xml
- src/main/java/org/passay/spring/SpringMessageResolver.java
- src/test/java/org/passay/spring/SpringMessageResolverTest.java
- src/test/java/org/passay/spring/SpringTest.java
I want to support the Spring's `MessageResolver` integrating the `MessageSource`.
What do you think?
> Supports the Spring's MessageResolver

- src/main/java/org/passay/HistoryRule.java
- src/main/java/org/passay/SourceRule.java
- src/test/java/org/passay/HistoryRuleTest.java
- src/test/java/org/passay/SourceRuleTest.java
We have a convention of using reportAllFailures controlling whether a rule only reports the first failure or all failures.
This PR adds that property to both the HistoryRule and SourceRule.
Note that this changes the default behavior, but this is probably the desired behavior.
See PR #68.
> Add reportAllFailures switch to history and source

- pom.xml
- src/main/java/org/passay/DigestHistoryRule.java
- src/test/java/org/passay/DigestHistoryRuleTest.java
Deprecating the old constructor allows us to stay API compatible.
See #76.
> Modify API to support BCrypt password history.

- src/main/java/org/passay/dictionary/TernaryTree.java
- src/main/java/org/passay/dictionary/TernaryTreeDictionary.java
Ternary Tree had some bugs in its printing implementation, like not printing the complete tree (or not printing at all small trees) on some platforms, first-level indentation was wrong (some second-level nodes appeared at the same indentation of the root node), etc.
Also optimized it to use a single StringBuilder instead of creating a whole lot of them, made the code shorter and cleaner, added command line option to print the full path on every line (easier for some analyses, and useful to see full words and not just their suffix), added indication of words ending in the middle of a path (prefix of other words), and changed the chars and spacing to make the printout look more like a standard tree diagram.
This helped me in analysing and understanding later modifications and their effect …
> Ternary Tree print improvements

- src/main/java/org/passay/dictionary/TernaryTree.java
- src/main/java/org/passay/dictionary/TernaryTreeDictionary.java
- src/test/java/org/passay/dictionary/TernaryTreeDictionaryPerfTest.java
In order to analyze the tree structure, implementation changes and optimizations, it is very useful to see statistics on the tree, specifically the histogram of how many nodes are at each depth (path length) in the tree. Other than just looking at the numbers, this makes it easy to copy&paste the data into Matlab/Octave to make nice graphs for visualizing performance comparisons etc.
These commits add this functionality to the tree, print them out in the (already existing) performance tests, and add a command line option to print them out on any given input.
> Ternary Tree node depth statistics

- src/main/java/org/passay/dictionary/AbstractWordList.java
- src/main/java/org/passay/dictionary/TernaryTreeDictionary.java
- src/main/java/org/passay/dictionary/WordList.java
- src/test/java/org/passay/dictionary/AbstractWordListTest.java
The previous implementation of MedianIterator didn't actually iterate over medians, it just started from the global median and then flip-flopped between higher and lower elements in sequential order (not sure how the sign flipping was better than just a simple sequential loop.)
The new implementation actually follows a full sequence of medians in a recursive-like manner. This allows search trees constructed from a sorted wordlist to be well-balanced, providing much better tree search performance. In the existing performance unit test it shows around 40% improvement in search speed.
If you merge the other PRs from today first, you can also print out the tree structure before/after this change and see how much more balanced it looks, or print out the node depth histogram and see the …
> Re-implement MedianIterator to use a proper sequence of medians

- src/main/java/org/passay/IllegalSequenceRule.java
- src/test/java/org/passay/IllegalSequenceRuleTest.java
- src/test/java/org/passay/PasswordValidatorTest.java
Rewrote IllegalSequenceRule to be much shorter and more efficient.
Other than the refactor, the functionality has also changed in one respect: if the illegal sequence length is set to e.g. 5 numerals, and the input password contains the sequence 1234567, then the new implementation will return the full illegal sequence 1234567 in the error result whereas the old implementation would return 3 illegal sequences 12345, 23456, 34567 (and not the full illegal sequence).
While it would be easy to support the previous functionality also after the refactor, I think the new behavior is more intuitive and informative, and the previously returned multiple subsequences, while technically correct, are not as useful (of course for every invalid sequence all subsequences of the configured length are …
> Simplify and optimize IllegalSequenceRule

- src/main/java/org/passay/dictionary/sort/ArraySorter.java
- src/main/java/org/passay/dictionary/sort/ArraysSort.java
- src/main/java/org/passay/dictionary/sort/BubbleSort.java
- src/main/java/org/passay/dictionary/sort/InsertionSort.java
- src/main/java/org/passay/dictionary/sort/QuickSort.java
- src/main/java/org/passay/dictionary/sort/SelectionSort.java
- src/test/java/org/passay/dictionary/sort/SorterTest.java
The build currently fails due to the japicmp plugin (even though it should be backward-compatible), so you can merge this when you're ready for a major version bump or whatever the policy for introducing such changes is.
> Add ArraySorter.sort default method to replace multiple implementations.

- src/main/java/org/passay/DigestDictionaryRule.java
For convenience, and to be consistent with all of the other dictionary rule classes which all have such a constructor.
> Add DigestDictionaryRule constructor that accepts a Dictionary.

- .travis/docker-run
- src/main/java/org/passay/PasswordGenerator.java
- src/main/java/org/passay/dictionary/AbstractFileWordList.java
- src/main/java/org/passay/dictionary/FileWordList.java
- src/main/java/org/passay/dictionary/MemoryMappedFileWordList.java
and running on JDK 8.
I see you just reverted the JDK upgrade due to these Buffer API changes causing trouble... I hope this fixes it and you can proceed with the upgrade. Would be a shame to be stuck on JDK8...
btw, to recreate the issue without this fix, build (mvn clean install) using JDK 9+ (just specify a JAVA_HOME pointing to it), and then run the tests without compiling (mvn surefire:test) using JDK8.
> Fix NoSuchMethodErrors using Buffer when compiling on JDK9+

- src/main/checkstyle/suppressions.xml
- src/main/java/org/passay/CzechCharacterData.java
- src/main/java/org/passay/CzechSequenceData.java
- src/test/java/org/passay/IllegalSequenceRuleTest.java
- Added czech data based on existing language enums
- Suppresed checkstyle MethodLength for tests due to length of DataProvider passwords in `IllegalSequenceRuleTest.java`
> Add CzechCharacterData and CzechSequenceData

- src/main/java/org/passay/GermanSequenceData.java
- src/test/java/org/passay/IllegalSequenceRuleTest.java
I have added the keyboard sequence for the standard german keyboard layout, where y and z (and some other special characters) are placed differently compared to the english layout. I did not copy the full tests, that are made for USQwerty, but this is not necessary - the functionality does not depend on the layout itself.
I was unsure about the naming - you may also name the enum entry "DEQwertz", if the focus is on ISO **country** codes and not language codes. "DE" would be the correct ISO 3166 Alpha-2 country code for Germany. In the long run, this would be correct, because e.g. Switzerland has a slightly different keyboard layout, than Germany.
> Added keyboard sequence for german QWERTZ layout.

- src/main/java/org/passay/RepeatCharacterRegexRule.java
- src/test/java/org/passay/RepeatCharacterRegexRuleTest.java
RepeatCharacterRegexRule uses String#format to create a regular expression. That operation is problematic in non-english locales. Define a specific locale for the operation.
Fixes #134.
> Avoid PatternSyntaxException formatting a regex.

- src/main/java/org/passay/PolishCharacterData.java
- src/main/java/org/passay/PolishSequenceData.java
Fix the lack of `ł` and `ń` characters in PolishCharacterData and PolishSequenceData. Check [alphabet](https://en.wikipedia.org/wiki/Polish_alphabet) in case of doubts.
> Add missing Polish characters: ł, ń

- pom.xml
- src/main/java/org/passay/PasswordGenerator.java
- src/test/java/org/passay/PasswordGeneratorTest.java
Relax generate API to accept a list of Rule so that rules that are naturally part of password validation can also be specified for password generation. The common use case is IllegalSequenceRule. Check the generated password against the given ruleset and try again up to 2 times to generate a valid password.
Resolves #152
> Relax PasswordGenerator API and add retry mech.

- src/main/java/org/passay/PasswordGenerator.java
Increment count before comparison with RETRY_LIMIT to avoid an additional generation that won't be used.
> Don't perform unnecessary generation.

- src/main/java/org/passay/AbstractValidationResult.java
- src/main/java/org/passay/PassayUtils.java
- src/main/java/org/passay/PasswordGenerator.java
- src/main/java/org/passay/UnicodeString.java
- src/main/java/org/passay/generate/CharacterAppender.java
- src/main/java/org/passay/generate/CharacterCharacteristicsAppender.java
- src/main/java/org/passay/generate/CharacterRuleAppender.java
- src/main/java/org/passay/generate/FillRemainingCharactersAppender.java
- src/main/java/org/passay/generate/PasswordGenerator.java
- src/main/java/org/passay/rule/IllegalSequenceRule.java
- src/test/java/org/passay/HeapDump.java
- src/test/java/org/passay/PasswordGeneratorTest.java
- src/test/java/org/passay/UnicodeStringTest.java
- src/test/java/org/passay/generate/PasswordGeneratorTest.java
Add support for leveraging Allowed and Illegal Character rules when generating passwords. Add PasswordGenerator.CharacterAppender interface to support extension. Rename PasswordGenerator#generatePassword to PasswordGenerator#generate and change to a no-args stateful implementation. Update UnicodePassword to support set operations on its characters. Fixes #40.
Fixes #145.
> v2: Improve PasswordGenerator
